package net.tc.proxysql;
// Generated 8-Dec-2016 2:36:43 PM by Hibernate Tools 5.2.0.CR1

/**
 * MysqlQueryRules generated by hbm2java
 */
public class MysqlQueryRules implements java.io.Serializable {

	private Integer ruleId;
	private int active;
	private String username;
	private String schemaname;
	private int flagIn;
	private String clientAddr;
	private String proxyAddr;
	private Integer proxyPort;
	private String digest;
	private String matchDigest;
	private String matchPattern;
	private int negateMatchPattern;
	private String reModifiers;
	private Integer flagOut;
	private String replacePattern;
	private Integer destinationHostgroup;
	private Integer cacheTtl;
	private Integer reconnect;
	private Integer timeout;
	private Integer retries;
	private Integer delay;
	private Integer mirrorFlagOut;
	private Integer mirrorHostgroup;
	private String errorMsg;
	private Integer stickyConn;
	private Integer multiplex;
	private Integer log;
	private int apply;
	private String comment;

	public MysqlQueryRules() {
	}

	public MysqlQueryRules(int active, int flagIn, int negateMatchPattern, int apply) {
		this.active = active;
		this.flagIn = flagIn;
		this.negateMatchPattern = negateMatchPattern;
		this.apply = apply;
	}

	public MysqlQueryRules(int active, String username, String schemaname, int flagIn, String clientAddr,
			String proxyAddr, Integer proxyPort, String digest, String matchDigest, String matchPattern,
			int negateMatchPattern, String reModifiers, Integer flagOut, String replacePattern,
			Integer destinationHostgroup, Integer cacheTtl, Integer reconnect, Integer timeout, Integer retries,
			Integer delay, Integer mirrorFlagOut, Integer mirrorHostgroup, String errorMsg, Integer stickyConn,
			Integer multiplex, Integer log, int apply, String comment) {
		this.active = active;
		this.username = username;
		this.schemaname = schemaname;
		this.flagIn = flagIn;
		this.clientAddr = clientAddr;
		this.proxyAddr = proxyAddr;
		this.proxyPort = proxyPort;
		this.digest = digest;
		this.matchDigest = matchDigest;
		this.matchPattern = matchPattern;
		this.negateMatchPattern = negateMatchPattern;
		this.reModifiers = reModifiers;
		this.flagOut = flagOut;
		this.replacePattern = replacePattern;
		this.destinationHostgroup = destinationHostgroup;
		this.cacheTtl = cacheTtl;
		this.reconnect = reconnect;
		this.timeout = timeout;
		this.retries = retries;
		this.delay = delay;
		this.mirrorFlagOut = mirrorFlagOut;
		this.mirrorHostgroup = mirrorHostgroup;
		this.errorMsg = errorMsg;
		this.stickyConn = stickyConn;
		this.multiplex = multiplex;
		this.log = log;
		this.apply = apply;
		this.comment = comment;
	}

	public Integer getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(Integer ruleId) {
		this.ruleId = ruleId;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSchemaname() {
		return this.schemaname;
	}

	public void setSchemaname(String schemaname) {
		this.schemaname = schemaname;
	}

	public int getFlagIn() {
		return this.flagIn;
	}

	public void setFlagIn(int flagIn) {
		this.flagIn = flagIn;
	}

	public String getClientAddr() {
		return this.clientAddr;
	}

	public void setClientAddr(String clientAddr) {
		this.clientAddr = clientAddr;
	}

	public String getProxyAddr() {
		return this.proxyAddr;
	}

	public void setProxyAddr(String proxyAddr) {
		this.proxyAddr = proxyAddr;
	}

	public Integer getProxyPort() {
		return this.proxyPort;
	}

	public void setProxyPort(Integer proxyPort) {
		this.proxyPort = proxyPort;
	}

	public String getDigest() {
		return this.digest;
	}

	public void setDigest(String digest) {
		this.digest = digest;
	}

	public String getMatchDigest() {
		return this.matchDigest;
	}

	public void setMatchDigest(String matchDigest) {
		this.matchDigest = matchDigest;
	}

	public String getMatchPattern() {
		return this.matchPattern;
	}

	public void setMatchPattern(String matchPattern) {
		this.matchPattern = matchPattern;
	}

	public int getNegateMatchPattern() {
		return this.negateMatchPattern;
	}

	public void setNegateMatchPattern(int negateMatchPattern) {
		this.negateMatchPattern = negateMatchPattern;
	}

	public String getReModifiers() {
		return this.reModifiers;
	}

	public void setReModifiers(String reModifiers) {
		this.reModifiers = reModifiers;
	}

	public Integer getFlagOut() {
		return this.flagOut;
	}

	public void setFlagOut(Integer flagOut) {
		this.flagOut = flagOut;
	}

	public String getReplacePattern() {
		return this.replacePattern;
	}

	public void setReplacePattern(String replacePattern) {
		this.replacePattern = replacePattern;
	}

	public Integer getDestinationHostgroup() {
		return this.destinationHostgroup;
	}

	public void setDestinationHostgroup(Integer destinationHostgroup) {
		this.destinationHostgroup = destinationHostgroup;
	}

	public Integer getCacheTtl() {
		return this.cacheTtl;
	}

	public void setCacheTtl(Integer cacheTtl) {
		this.cacheTtl = cacheTtl;
	}

	public Integer getReconnect() {
		return this.reconnect;
	}

	public void setReconnect(Integer reconnect) {
		this.reconnect = reconnect;
	}

	public Integer getTimeout() {
		return this.timeout;
	}

	public void setTimeout(Integer timeout) {
		this.timeout = timeout;
	}

	public Integer getRetries() {
		return this.retries;
	}

	public void setRetries(Integer retries) {
		this.retries = retries;
	}

	public Integer getDelay() {
		return this.delay;
	}

	public void setDelay(Integer delay) {
		this.delay = delay;
	}

	public Integer getMirrorFlagOut() {
		return this.mirrorFlagOut;
	}

	public void setMirrorFlagOut(Integer mirrorFlagOut) {
		this.mirrorFlagOut = mirrorFlagOut;
	}

	public Integer getMirrorHostgroup() {
		return this.mirrorHostgroup;
	}

	public void setMirrorHostgroup(Integer mirrorHostgroup) {
		this.mirrorHostgroup = mirrorHostgroup;
	}

	public String getErrorMsg() {
		return this.errorMsg;
	}

	public void setErrorMsg(String errorMsg) {
		this.errorMsg = errorMsg;
	}

	public Integer getStickyConn() {
		return this.stickyConn;
	}

	public void setStickyConn(Integer stickyConn) {
		this.stickyConn = stickyConn;
	}

	public Integer getMultiplex() {
		return this.multiplex;
	}

	public void setMultiplex(Integer multiplex) {
		this.multiplex = multiplex;
	}

	public Integer getLog() {
		return this.log;
	}

	public void setLog(Integer log) {
		this.log = log;
	}

	public int getApply() {
		return this.apply;
	}

	public void setApply(int apply) {
		this.apply = apply;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
