package net.tc.proxysql;
// Generated 8-Dec-2016 2:36:43 PM by Hibernate Tools 5.2.0.CR1

/**
 * MysqlServers generated by hbm2java
 */
public class MysqlServers implements java.io.Serializable {

	private MysqlServersId id;
	private String status;
	private int weight;
	private int compression;
	private int maxConnections;
	private int maxReplicationLag;
	private int useSsl;
	private int maxLatencyMs;
	private String comment;

	public MysqlServers() {
	}

	public MysqlServers(MysqlServersId id, String status, int weight, int compression, int maxConnections,
			int maxReplicationLag, int useSsl, int maxLatencyMs, String comment) {
		this.id = id;
		this.status = status;
		this.weight = weight;
		this.compression = compression;
		this.maxConnections = maxConnections;
		this.maxReplicationLag = maxReplicationLag;
		this.useSsl = useSsl;
		this.maxLatencyMs = maxLatencyMs;
		this.comment = comment;
	}

	public MysqlServersId getId() {
		return this.id;
	}

	public void setId(MysqlServersId id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	public int getCompression() {
		return this.compression;
	}

	public void setCompression(int compression) {
		this.compression = compression;
	}

	public int getMaxConnections() {
		return this.maxConnections;
	}

	public void setMaxConnections(int maxConnections) {
		this.maxConnections = maxConnections;
	}

	public int getMaxReplicationLag() {
		return this.maxReplicationLag;
	}

	public void setMaxReplicationLag(int maxReplicationLag) {
		this.maxReplicationLag = maxReplicationLag;
	}

	public int getUseSsl() {
		return this.useSsl;
	}

	public void setUseSsl(int useSsl) {
		this.useSsl = useSsl;
	}

	public int getMaxLatencyMs() {
		return this.maxLatencyMs;
	}

	public void setMaxLatencyMs(int maxLatencyMs) {
		this.maxLatencyMs = maxLatencyMs;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
