package net.tc.proxysql;
// Generated 8-Dec-2016 2:36:43 PM by Hibernate Tools 5.2.0.CR1

/**
 * MysqlReplicationHostgroups generated by hbm2java
 */
public class MysqlReplicationHostgroups implements java.io.Serializable {

	private int writerHostgroup;
	private int readerHostgroup;
	private String comment;

	public MysqlReplicationHostgroups() {
	}

	public MysqlReplicationHostgroups(int writerHostgroup, int readerHostgroup) {
		this.writerHostgroup = writerHostgroup;
		this.readerHostgroup = readerHostgroup;
	}

	public MysqlReplicationHostgroups(int writerHostgroup, int readerHostgroup, String comment) {
		this.writerHostgroup = writerHostgroup;
		this.readerHostgroup = readerHostgroup;
		this.comment = comment;
	}

	public int getWriterHostgroup() {
		return this.writerHostgroup;
	}

	public void setWriterHostgroup(int writerHostgroup) {
		this.writerHostgroup = writerHostgroup;
	}

	public int getReaderHostgroup() {
		return this.readerHostgroup;
	}

	public void setReaderHostgroup(int readerHostgroup) {
		this.readerHostgroup = readerHostgroup;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
