package net.tc.proxysql;
// Generated 8-Dec-2016 2:36:43 PM by Hibernate Tools 5.2.0.CR1

/**
 * MysqlUsersId generated by hbm2java
 */
public class MysqlUsersId implements java.io.Serializable {

	private String username;
	private int backend;

	public MysqlUsersId() {
	}

	public MysqlUsersId(String username, int backend) {
		this.username = username;
		this.backend = backend;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getBackend() {
		return this.backend;
	}

	public void setBackend(int backend) {
		this.backend = backend;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MysqlUsersId))
			return false;
		MysqlUsersId castOther = (MysqlUsersId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& (this.getBackend() == castOther.getBackend());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + this.getBackend();
		return result;
	}

}
