package net.tc.proxysql;
// Generated 8-Dec-2016 2:36:43 PM by Hibernate Tools 5.2.0.CR1

/**
 * RuntimeMysqlUsers generated by hbm2java
 */
public class RuntimeMysqlUsers implements java.io.Serializable {

	private RuntimeMysqlUsersId id;
	private String password;
	private int active;
	private int useSsl;
	private int defaultHostgroup;
	private String defaultSchema;
	private int schemaLocked;
	private int transactionPersistent;
	private int fastForward;
	private int frontend;
	private int maxConnections;

	public RuntimeMysqlUsers() {
	}

	public RuntimeMysqlUsers(RuntimeMysqlUsersId id, int active, int useSsl, int defaultHostgroup, int schemaLocked,
			int transactionPersistent, int fastForward, int frontend, int maxConnections) {
		this.id = id;
		this.active = active;
		this.useSsl = useSsl;
		this.defaultHostgroup = defaultHostgroup;
		this.schemaLocked = schemaLocked;
		this.transactionPersistent = transactionPersistent;
		this.fastForward = fastForward;
		this.frontend = frontend;
		this.maxConnections = maxConnections;
	}

	public RuntimeMysqlUsers(RuntimeMysqlUsersId id, String password, int active, int useSsl, int defaultHostgroup,
			String defaultSchema, int schemaLocked, int transactionPersistent, int fastForward, int frontend,
			int maxConnections) {
		this.id = id;
		this.password = password;
		this.active = active;
		this.useSsl = useSsl;
		this.defaultHostgroup = defaultHostgroup;
		this.defaultSchema = defaultSchema;
		this.schemaLocked = schemaLocked;
		this.transactionPersistent = transactionPersistent;
		this.fastForward = fastForward;
		this.frontend = frontend;
		this.maxConnections = maxConnections;
	}

	public RuntimeMysqlUsersId getId() {
		return this.id;
	}

	public void setId(RuntimeMysqlUsersId id) {
		this.id = id;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public int getUseSsl() {
		return this.useSsl;
	}

	public void setUseSsl(int useSsl) {
		this.useSsl = useSsl;
	}

	public int getDefaultHostgroup() {
		return this.defaultHostgroup;
	}

	public void setDefaultHostgroup(int defaultHostgroup) {
		this.defaultHostgroup = defaultHostgroup;
	}

	public String getDefaultSchema() {
		return this.defaultSchema;
	}

	public void setDefaultSchema(String defaultSchema) {
		this.defaultSchema = defaultSchema;
	}

	public int getSchemaLocked() {
		return this.schemaLocked;
	}

	public void setSchemaLocked(int schemaLocked) {
		this.schemaLocked = schemaLocked;
	}

	public int getTransactionPersistent() {
		return this.transactionPersistent;
	}

	public void setTransactionPersistent(int transactionPersistent) {
		this.transactionPersistent = transactionPersistent;
	}

	public int getFastForward() {
		return this.fastForward;
	}

	public void setFastForward(int fastForward) {
		this.fastForward = fastForward;
	}

	public int getFrontend() {
		return this.frontend;
	}

	public void setFrontend(int frontend) {
		this.frontend = frontend;
	}

	public int getMaxConnections() {
		return this.maxConnections;
	}

	public void setMaxConnections(int maxConnections) {
		this.maxConnections = maxConnections;
	}

}
