package net.tc.proxysql;
// Generated 8-Dec-2016 2:36:43 PM by Hibernate Tools 5.2.0.CR1

/**
 * Scheduler generated by hbm2java
 */
public class Scheduler implements java.io.Serializable {

	private Integer id;
	private int active;
	private int intervalMs;
	private String filename;
	private String arg1;
	private String arg2;
	private String arg3;
	private String arg4;
	private String arg5;
	private String comment;

	public Scheduler() {
	}

	public Scheduler(int active, int intervalMs, String filename, String comment) {
		this.active = active;
		this.intervalMs = intervalMs;
		this.filename = filename;
		this.comment = comment;
	}

	public Scheduler(int active, int intervalMs, String filename, String arg1, String arg2, String arg3, String arg4,
			String arg5, String comment) {
		this.active = active;
		this.intervalMs = intervalMs;
		this.filename = filename;
		this.arg1 = arg1;
		this.arg2 = arg2;
		this.arg3 = arg3;
		this.arg4 = arg4;
		this.arg5 = arg5;
		this.comment = comment;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public int getIntervalMs() {
		return this.intervalMs;
	}

	public void setIntervalMs(int intervalMs) {
		this.intervalMs = intervalMs;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getArg1() {
		return this.arg1;
	}

	public void setArg1(String arg1) {
		this.arg1 = arg1;
	}

	public String getArg2() {
		return this.arg2;
	}

	public void setArg2(String arg2) {
		this.arg2 = arg2;
	}

	public String getArg3() {
		return this.arg3;
	}

	public void setArg3(String arg3) {
		this.arg3 = arg3;
	}

	public String getArg4() {
		return this.arg4;
	}

	public void setArg4(String arg4) {
		this.arg4 = arg4;
	}

	public String getArg5() {
		return this.arg5;
	}

	public void setArg5(String arg5) {
		this.arg5 = arg5;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
